spring.application.name: interfero
---
interfero.database:
  enabled: false
  vendor: postgres
  driver-class-name: org.postgresql.Driver
---
interfero.directories:
  data: /opt/interfero/data
---
management:
  server.port: 8081
  endpoints.web:
    base-path: /
    exposure.include: health,prometheus
    path-mapping:
      prometheus: metrics
  metrics.tags:
    application: ${spring.application.name}
---
springdoc:
  swagger-ui.enabled: false
  api-docs:
    enabled: false
    path: /api-docs/v3
---
logging.level:
  org.springframework: WARN
  org.springdoc: WARN
  org.apache: WARN
  com.tngtech: WARN
  com.zaxxer: WARN
