interfero.pulsar.clusters:
  cluster-a:
    client.service-url: http://localhost:16650
    admin.service-url: http://localhost:18080
  cluster-b:
    client.service-url: http://localhost:26650
    admin.service-url: http://localhost:28080
---
interfero.admin.account.password: $2a$12$Vsho9XvQ.BtnuU72PgRGN.R0ObbM7P4KRDfOlmWhAWiC2AN/NDqE6 # secret
---
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
---
logging.level:
  io.interfero: DEBUG
